using Eatabase.API.Configuration;

var builder = WebApplication.CreateBuilder(args);

builder.ConfigureServices();

var app = builder.Build();

app.ConfigureMiddlewares();
app.ConfigureEndpoints();

app.Run();

// Program generated by top-level statements is not publicly accessible by default
// This makes it accessible to the WebApplicationFactory in Integration Tests
// https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-9.0&pivots=xunit#basic-tests-with-the-default-webapplicationfactory
public partial class Program;
